language: none

build:
  ci:
    - cat /etc/issue
   
resources:   
  
  - name: TG
    type: gitRepo
    integration: github
    pointer:
      sourceName: ambarish2012/key-value-sample
      branch: master
jobs:

  - name: testjob
    type: runSh
    steps:
      - IN: testgitrepo
      - TASK: 
        - script: echo $TG_PATH
        - script: echo $TG_STATE
        
        
